### ISSUE TITLE
A string of characters that are all the same used as a seed, no matter the length, results in the same output.

### ISSUE THREAD

**Issue by ChildishGiant** [davidbau/seedrandom#48]
```
Math.seedrandom("a")
Math.random() -> 0.43449421599986604
Math.seedrandom("aa")
Math.random() -> 0.43449421599986604
Math.seedrandom("aaaaaaa")
Math.random() -> 0.43449421599986604
```

**Comment by davidbau** [comment]
From the readme:

> The standard ARC4 key scheduler cycles short keys, which means that seedrandom('ab') is equivalent to seedrandom('abab') and 'ababab'. Therefore it is a good idea to add a terminator to avoid trivial equivalences on short string seeds, e.g., Math.seedrandom(str + '\0'). Starting with version 2.0, a terminator is added automatically for non-string seeds, so seeding with the number 111 is the same as seeding with '111\0'.

In the interest of compatibility, we are staying with this scheme.

**Comment by ChildishGiant** [comment]
Okay, thanks for the explaination 😄

**Comment by ryan-williams** [comment]
I ran into this issue because I noticed `"11"` and `"111"` generate the same random numbers.

My seed is a `number`, but I am stringifying it because [`@types/seedrandom`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/seedrandom/index.d.ts) doesn't appear to support passing a `number` as seed. I also don't see examples of doing so in the README/docs. Is that supported? Do the types need updating?
